### ISSUE TITLE
Arduino due warning: "pgm_read_byte" redefined 

### ISSUE THREAD

**Issue by mayerf70** [lasselukkari/aWOT#102]
In file included from src/main.cpp:2:0:
lib/aWOT/src/aWOT.h:68:0: warning: "pgm_read_byte" redefined
 #define pgm_read_byte(ptr) (unsigned char)(*ptr)
 
In file included from /home/am/.platformio/packages/framework-arduino-sam/cores/arduino/Arduino.h:31:0,
                 from src/main.cpp:1:
/home/am/.platformio/packages/framework-arduino-sam/cores/arduino/avr/pgmspace.h:102:0: note: this is the location of the previous definition
 #define pgm_read_byte(addr) (*(const unsigned char *)(addr))

**Comment by lasselukkari** [comment]
This was added a few years ago when the DUE core did not have this built in. I'll take a look what the situation is at the moment. Maybe it can be just removed.

**Comment by mayerf70** [comment]
Thank you really great library!

**Comment by lasselukkari** [comment]
Thanks! If you like it you can give it a star.
