### ISSUE TITLE
Feature Request / Bug On Some Platforms:  Reduce memory footprint by wrapping all C strings in `F(...)`

### ISSUE THREAD

**Issue by EmperorArthur** [lasselukkari/aWOT#106]
Hello,

I was recently evaluating your library to replace our custom Arduino HTTP Server implementation.  Of all the libraries examined so far, yours is definitely the most polished, and certainly has better routing capabilities than the nested if statements ours uses.  Please do not take my suggestions as thinking your library is "bad."

In the process of evaluating your library, I noticed that it uses 1398 bytes of RAM.  I believe this is because, despite importing "Arduino.h", the library uses raw C strings for everything.  Those strings are always stored in RAM, just sitting there doing nothing but taking up space.

This limits what devices the library can be run on, and/or the amount of data processing that is available when using this library.

# Suggested Fix
`#include <WString.h>` and then use `F(<HttpStatus_reasonPhrase>)`.  An alternate approach for some code is to use [this](https://github.com/j-ulrich/http-status-codes-cpp) repository, with sleight [modifications](https://github.com/j-ulrich/http-status-codes-cpp/issues/15).

**Comment by EmperorArthur** [comment]
If you are interested, I should be able to submit a pull request to resolve this issue.

**Comment by lasselukkari** [comment]
Hi.

I have been trying to avoid the dependency to String class. Maybe there is no good reason for that. Feel free to make a pull request.

**Comment by EmperorArthur** [comment]
Thanks for the response.  I used [this tool](https://sparks.gogo.co.nz/avr-ram-use.html) to examine what is being stored in RAM, and took a deep dive in the code.

It looks like most of the usage I was seeing was because of the 128 and 1024 buffers.  You may want to document that somewhere.  Especially since some of us (me mostly) are used to using things like [ArduinoStreamUtils](https://github.com/bblanchon/ArduinoStreamUtils).

However, I believe I can save at least 50 bytes of RAM just by wrapping the C strings in `m_processMethod` with:
```
#define FC(string_literal) String(F(string_literal)).c_str()
FC("some string")
```

I am continuing to investigate, and will send a PR soon.

**Comment by EmperorArthur** [comment]
That macro approach didn't work out as well as I'd like, however standard Arduino F strings were the solution.

PR #109 saves 98 bytes worth of RAM, and actually seems to decrease flash usage by 54 bytes as well.  I assume the optimizer is able to remove or combine more code.

**Comment by lasselukkari** [comment]
PR merged.
