### ISSUE TITLE
Feature Request / Documentation Question: Custom 404 page / Default Route

### ISSUE THREAD

**Issue by EmperorArthur** [lasselukkari/aWOT#107]
Hello,

I was recently evaluating your library to replace our custom Arduino HTTP Server implementation. Of all the libraries examined so far, yours is definitely the most polished, and certainly has better routing capabilities than the nested if statements ours uses. Please do not take my suggestions as thinking your library is "bad."

We would like to be able to serve custom fallback pages, and I can not find a method to do so.  Does this ability exist?  If this is not possible, it would be a much appreciated feature.

These are the three use cases we currently have, and why I believe it is important:
* A custom 404 page.
* A generic reply to OPTIONS requests with all the "Access-Control-Allow-..." headers as permissible as possible.
* (Low priority) A "Method Not Allowed" page for non GET requests that do not match a page that supports them.

# Proposed Solution
I believe replacing/appending `return m_response.sendStatus(404);` in "Application::m_process()" with a check for a custom "Router::Middleware" would easily enable this function.

**Comment by EmperorArthur** [comment]
If you are interested, I should be able to submit a pull request to resolve this issue.

**Comment by lasselukkari** [comment]
Hi. Thanks for the feedback.

Did you see the [CustomNotFound](https://github.com/lasselukkari/aWOT/tree/master/examples/CustomNotFound) example? I believe it does what you want.

A generic reply to OPTIONS can be done with a middleware that is set to be the first one with `app.use()`. Then just check the `request.method()` type and if it's OPTIONS send your reply with the headers and then call  `res.end()` to stop the middleware chain. The [AuthMiddleware](https://github.com/lasselukkari/aWOT/blob/master/examples/AuthMiddleware/AuthMiddleware.ino) example kinda works the same way.

The third one in the list would be hard to implement and imo not a good idea considering the benefits. If you really need it you can use `app.use();` with or without path and then just check the method type manually.

**Comment by lasselukkari** [comment]
I agree that it could make sense to implement the feature for the custom not found page. I can do that. I have mixed feelings about the dedicated middleware for the options method.

**Comment by lasselukkari** [comment]
How about something like this: https://github.com/lasselukkari/aWOT/compare/app-not-found?expand=1

**Comment by lasselukkari** [comment]
After giving it a second thought I could add back the overloaded versions of app.METHOD() that do not specify paths. I had these before, but removed them at some point because I had no use cases for them personally. The required changes are really small.

**Comment by lasselukkari** [comment]
It was a 5 minute job: https://github.com/lasselukkari/aWOT/compare/app-not-found...method-middleware?expand=1

**Comment by EmperorArthur** [comment]
Awesome!  I really appreciate everything you're doing.

It really looks like that last one is convenient, but could also be done by documentation.

**Comment by lasselukkari** [comment]
These features have been now merged to master.
