### ISSUE TITLE
routing use .use appends 404 error after content is served

### ISSUE THREAD

**Issue by shanevanj** [lasselukkari/aWOT#11]
Using hello world example:

Output in browser if app.get("", &indexCmd); is  used to route

# **Greetings middle earth!**

Output in browser if app.use(&indexCmd); is used to route

# **Greetings middle earth!**
HTTP/1.0 404 Not Found Content-Type: text/html
# ** 404 Not Found**

I want to deal with the routing myself as I will serve files from SD card as well as using Ajax

**Comment by lasselukkari** [comment]
I noticed this too a while a go. The fix should be easy. Give me a few days.

**Comment by shanevanj** [comment]
Thanks so much - I would have given it a go, but my skills are just not put to your code - great library !

 
Shane van Jaarsveldt
Tel: +27 11 469 4750  Cel: +27 82 601 0499  Fax: +27 11 469 3370
