### ISSUE TITLE
Compiler error for Ehernet example

### ISSUE THREAD

**Issue by argo9** [lasselukkari/aWOT#129]
Compiler exits in this way:
`cannot declare variable 'server' to be of abstract type 'EthernetServer'`

Last library release installed, arduino IDE 1.8.12, ESP32 1.0.6 eith ethernet library and w5500 board.

Thanks :)

**Comment by argo9** [comment]
Applied this solution:

**Comment by ArminPP** [comment]
As in the [readme](https://github.com/lasselukkari/aWOT#readme) of aWot described, there is a 'hack' in [server.h](https://github.com/espressif/arduino-esp32/issues/2704#issuecomment-657217611) to do, then it should work ;-)

p.s. unfortunately this doesn't work with asyncwebserver :-(

**Comment by argo9** [comment]
> As in the [readme](https://github.com/lasselukkari/aWOT#readme) of aWot described, there is a 'hack' in [server.h](https://github.com/espressif/arduino-esp32/issues/2704#issuecomment-657217611) to do, then it should work ;-)
> 
> p.s. unfortunately this doesn't work with asyncwebserver :-(

Thanks man!! We were writing the solution the same time :D

Yeah... also async web server would have been a nice implementation... :(

**Comment by lasselukkari** [comment]
I'm happy you got it working. @ArminPP thanks for helping to take care if this issue.
