### ISSUE TITLE
Multiple query parameters

### ISSUE THREAD

**Issue by soccou** [lasselukkari/aWOT#13]
Hi,

First thanks for sharing your excellent library. I had spent quite a while looking for something like this.

However, it appears that there may be an issue with trying to pass more than one query parameter? or perhaps I am doing something wrong. (that is always very possible... )

Example code 
```
 app.get("/c", &correctionGetRequest);
.
.
.
void correctionGetRequest(Request &req, Response &res) {
  char * correctionValue = req.query("VAL");
  char * chanNumberParam = req.query("ID"); 
  int chanNumber = atoi(chanNumberParam);
  
  res.success("text/html");
  
  res.print("chanNumber: ");
  res.print(chanNumber);	
  res.print("<br/>");
  res.print("correctionValue:");
  res.print(correctionValue);	
  res.print("<br/>");
  
```

It seems like when you look at the values they both equal value passed for "ID" unless you don't pass that value at all, then the other parameter works, examples :  

```
/c?ID=1&VAL=2.63"
chanNumber: 1<br/>correctionValue:1<br/>

> curl "http://192.168.1.147/c?ID=2&VAL=2.63"
chanNumber: 2<br/>correctionValue:2<br/>

> curl "http://192.168.1.147/c?ID=3&VAL=2.63"
chanNumber: 3<br/>correctionValue:3<br/>

> curl "http://192.168.1.147/c?VAL=2.63"
chanNumber: 0<br/>correctionValue:2.63<br/>

> curl "http://192.168.1.147/c?VAL=2.63&ID=1"
chanNumber: 1<br/>correctionValue:1<br/>

> curl "http://192.168.1.147/c?VAL=2.63&ID=2"
chanNumber: 2<br/>correctionValue:2<br/>

```

Any suggestions?

**Comment by lasselukkari** [comment]
Hello! Sorry for the delayed reply.

The existing api to read query parameters maybe wasn't the most intuitive. It was reading the value to an internal buffer and the buffer was overwritten as soon the next value was read.

I update api so that the buffer for the value is given as a parameter. These changes were merged in pr https://github.com/lasselukkari/aWOT/pull/14

```
void correctionGetRequest(Request &req, Response &res) {
  char correctionValue[64];
  char chanNumberParam[64];
  
  req.query("VAL", correctionValue, 64);
  req.query("ID", chanNumberParam, 64);
  int chanNumber = atoi(chanNumberParam);
  
  res.success("text/html");
  res.print("chanNumber: ");
  res.print(chanNumber);  
  res.print("<br/>");
  res.print("correctionValue:");
  res.print(correctionValue); 
  res.print("<br/>");
}
```

**Comment by soccou** [comment]
Nice, thanks for the reply and the patch.
I will give it a try.
