### ISSUE TITLE
Upload files from browser and store them into LittleFS/SPIFFS/SD

### ISSUE THREAD

**Issue by AppsByDavideV** [lasselukkari/aWOT#136]
Hello, 
I found this library very useful for working with ethernet and WiFi at the same time.
I have been able to serve files from SD (using ESP32+ SDcard reader) to the browser using one of your examples, but due to my lack of knowledge about how library works and data flow, I don't understand how to send files from browser to be stored in the SD (or SPIFFS etc..).

I think it can be done in a similar way as OTA update, but I can't get it  :(
Is there any example?

Thank you in advance.
/Davide

**Comment by candide33** [comment]
hi
i tested transfer of a file from  a browser Firefox to esp with awot webserver, but i am stuck when i want to transfert more then 1500 bytes.
by example, if file size is around 4586 bytes, in server i can see req.left = 4806 and req.available = 1565 
in this case, i am able to read the 1565 first bytes, but no more...

how to read the total size of file in server side ? 

thanks for your help

**Comment by lasselukkari** [comment]
available() only returns you the the amount of bytes in the buffer available immediately for read. it does not mean the the next call would not return more data.  Can you show me your code you are using. Your loop for reading should look something like:

```cpp
while (req.left()) {
   // also deal with clients that stop sending data here

  file.write(req.read());
}
```

**Comment by candide33** [comment]
Thanks for your help and after more tests, this is what i can see:
- for an upload Firefox => esp8266
yes, req.left give the number of bytes to be sent to server and req.available give the part available in stream. 
=> until req.left=0, we have to take bytes available in stream and wait for reception of next one available when req.available =0, and if we follow this process,  upload is working.  
Next issues found : 
 => we have to remove a header of 4 lines, and also similar footer manually...
 => after req.available and req.left are integers => we cannot receive a file with size > 32000bytes...

- for download esp =>Firefox, file is also limited to 32000 bytes and a footer is added, but here i didn't find a way to remove it in aWOT server

Thnaks again for this good library.

**Comment by lasselukkari** [comment]
Unfortunately I have no idea what you mean by header and footer.

**Comment by candide33** [comment]
at last, what i wanted to do is working, thanks for your help.

in fact i was working at a wrapper raWOT, to use aWOT library with B4R and now it is working, and a small project is available to show what we can do with aWOT and B4R

more information on raWOT in B4R forum.
https://www.b4x.com/android/forum/threads/rawot.135993/


thanks again for this good library and for your support


----- Mail original -----
De: "Lasse Lukkari" ***@***.***>
À: "lasselukkari/aWOT" ***@***.***>
Cc: "candide33" ***@***.***>, "Comment" ***@***.***>
Envoyé: Mercredi 10 Novembre 2021 22:27:47
Objet: Re: [lasselukkari/aWOT] Upload files from browser and store them into LittleFS/SPIFFS/SD (Issue #136)





Unfortunately I have no idea what you mean by header and footer. 

— 
You are receiving this because you commented. 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .

**Comment by gcharles81** [comment]
Hello Thanks for this great library is there any working example for uploading files from a browser and store them in the SD or SPIFFS Thanks

**Comment by LOGOLEX** [comment]
Hey, i just tried out to get your examlple to work.
But after i upload a File over Ethernet adapter, there is one Byte more at the beginning of the File, so it is corrupted.
Upload over Wifi works properly.
The uploads add a HEX 0xFF as first Byte
I'm running this code on a ESP32 WROOM dev Board with attached ENC28J60

Where is my fault?


> Actually now that I'm thinking this again the previous solution was maybe not that smart way of doing this. Semantically more correct would maybe be a PUT request to `/files/filename.ext` without using the headers. You can then use route parameter to read the filename:
> 
> ```c++
> void upload(Request &req, Response &res) {
>   char filename[64];
>   
>   req.route("filename", filename, 64);
> 
>   File file = SPIFFS.open(filename, "w");
> 
>   while (req.left()) {
>    // also deal with clients that stop sending data here
> 
>     file.write(req.read());
>   }
> 
>   file.close();
>   res.sendStatus(204);
> }
> 
> void setup() {
>   app.put("/files/:filename", &upload);;
> } 
> ```
> 
> And the form would then look like
> 
> ```
> <html>
>   <body>
>     <form id="form">
>       <input id="file" type="file" />
>       <input type="submit" value="Send" />
>     </form>
>   </body>
>   <script>
>     const form = document.getElementById("form");
>     form.onsubmit = function (e) {
>       e.preventDefault();
>       const file = document.getElementById("file").files[0];
>       const fileName = file.name;
>       fetch("/files/" + fileName, {
>         method: "PUT",
>         body: file,
>       }).then((response) => {
>         if (!response.ok) {
>           return alert("File upload failed");
>         }
>         alert("File upload succeeded");
>       });
>     };
>   </script>
> </html>
> ```
> 
> Again this is completely untested code. I did not even compile any of it.

**Comment by lasselukkari** [comment]
Hi! What does `req.available()` return when you try to read the first time? 

You could try changing your code to something like this:
```cpp
while (req.left()) {
   if(req.available()){
      file.write(req.read());
  }
}

```

There are a lot better options than the ENC28J60 for the ESP32 if you need an Ethernet connection.

**Comment by LOGOLEX** [comment]
Hello lasselukkari,

my test Upload contains 9 bytes.
req.available() returns "0" at the first call, on the second call 8. then every call one less.

However, just calling req.available() one time without "if" statement solved my problem.
I changed the code to your example and now it works. (eventually you could explain why?)

If there are better options to get Ethernet on ESP32, what do you recommend?
With the ENC28j60 i get a 10 MBit/s connection. In this case this is enough. But i would be pleased to have a better option for future projects.

Thank you!


> Hi! What does `req.available()` return when you try to read the first time?
> 
> You could try changing your code to something like this:
> 
> ```c++
> while (req.left()) {
>    if(req.available()){
>       file.write(req.read());
>   }
> }
> ```
> 
> There are a lot better options than the ENC28J60 for the ESP32 if you need an Ethernet connection.

**Comment by lasselukkari** [comment]
> However, just calling req.available() one time without "if" statement solved my problem. I changed the code to your example and now it works. (eventually you could explain why?)

It's "feature" of the Ethernet library you are using. Nothing to do with this library.
