### ISSUE TITLE
Websocket server 

### ISSUE THREAD

**Issue by Sampozzo** [lasselukkari/aWOT#138]
Hello, i can't find info on this topic... 

Is it possibile to use aWOT library as a websocket server? 
If yes, can you provider an example please?

Thank you very much again.

**Comment by lasselukkari** [comment]
Hi. Unfortunately not. 

As a side note websockets on these tiny microcontroller become complicated really fast. It's easy when you have just one connected client at the time but once you open more connections the state management becomes complicated and it's easy run out of sockets. This is why I have personally preferred polling instead. It maybe isn't as sophisticated solution but starting from the same know state when a client makes a request and closing the connection after the request keeps things simple. I have used 50 ms interval for the polling on ESP8266 and ESP32 so the updates feel almost instant.

**Comment by Sampozzo** [comment]
Thank you very much @lasselukkari

**Comment by Sampozzo** [comment]
Hello, just in case someone else need info on this topic, i found this library that works great with aWOT: 

https://github.com/skaarj1989/mWebSockets

This is the only one that works over ethernet too. Now i have a working project with aWOT for static files, websocket and ethernet connection.

**Comment by lasselukkari** [comment]
Thanks for the information!
