### ISSUE TITLE
net::ERR_CONNECTION_REFUSED using ethernet

### ISSUE THREAD

**Issue by infrafast** [lasselukkari/aWOT#150]
Hello, thanks for your lib.
I use it with ESP32-S3 and the ethernet server fix you provided

When using WiFi, all works good,

when using ethernet,
I get net::ERR_CONNECTION_REFUSED on (random) file, for instance when the client try :

GET http://192.168.0.81/medium.gif net::ERR_CONNECTION_REFUSED

On the server side (ESP) I get no trace, that medium.gif has been requested.

Any help appreciated.
BR

**Comment by lasselukkari** [comment]
The server code really doesn't know where the connection is coming from. Is it wifi or ethernet or what ever. It just uses the client interface that is common to all client classes. The error you are seeing indicates that the ethernet part refused the whole connection. If there is no connection there is nothing for the web server to process.

My suggestion is to verify that your ethernet connection is working in the first place using some sketch that does not use any external libraries. See the examples of your ethernet connection library.

**Comment by infrafast** [comment]
Thank you for having a look to that. I tested the ethernet connexion : working good. The issue is that it serves the pages and content until  a certain point. Then, it stops. This is difficult to reproduce so I'll try to further investigate and providde more details,. This will take a while so we can keep the issue closed for the time being.

**Comment by lasselukkari** [comment]
Sounds like there is a memory leak or something similar somewhere if it works at first and then stops responding.

I would suggest removing ALL other code and included libraries and replacing the handler functions with print calls that just emulate your expected responses. Does it still give you the problems? If it does please provide a minimum example sketch that reproduces the problem.

**Comment by infrafast** [comment]
Hello I made additionnal test as per your advise.

I created a function that emulates the handler:

#define MIME_TYPES_MAX 14
    void fileServer(Request &req, Response &res){
      
      const char * path = req.path();
    
      String mimeTypes[MIME_TYPES_MAX][2] ={
        {"html",  "text/html"},
        {"js",    "application/javascript"},
        {"json",  "application/json"},
        {"jpeg",  "image/jpeg"},
        {"jpg",   "image/jpeg"},
        {"gif",   "image/gif"},
        {"png",   "image/png"},  
        {"txt",   "text/plain"},  
        {"htm",   "text/html"},
        {"xml",   "application/xml"},  
        {"css",   "text/css"},  
        {"gz",    "application/gzip"},  
        {"zip",   "application/zip"},
        {"ttf",   "font/ttf"}
      };
      String mimeType = mimeTypes[0][1];  //default to text/html
      for (uint8_t i=0;i<MIME_TYPES_MAX;i++){
        if (String(path).endsWith(mimeTypes[i][0])) mimeType = mimeTypes[i][1];
      }
      res.set("Content-Type", mimeType.c_str());

      Serial.printf("\n\tserving: %s <%s>",path, mimeType.c_str());
 
      if(strcmp(path, "/") == 0){
        // we serve the main html page so it will request all the other files like scripts, images, css...
        File file = LittleFS.open("/webapp/indexnozip.html");
        while (file.available()) res.write(file.read());
        file.close();
      }else if (String(path).endsWith(".js")){
        // the main html body <onload> balise calls for initIndex() so we implement it minimal
        res.println("function initIndex(){srv = 'ws://'+window.location.host+':3000';wsocket = new WebSocket(srv);wsocket.onopen = function(evt) {console.log('wsocketh opened');};wsocket.onclose = function(evt) { console.log('wsocketh closed'); };wsocket.onmessage = function(evt) {console.log(\"wsocketh received:<\"+evt.data+\">\");};};");
      }else{
        // for gif, jpg , css and all other we do nothing
      }
      res.end();           
    }


This works very good, no issue, hereis the log on the ESP32 serial:

Webapp connected eth
        serving: / <text/html>
Webapp connected eth
        serving: /style.css <text/css>
Webapp connected eth
        serving: /gettext.iife.min.js <application/javascript>
Webapp connected eth
        serving: /interval.js <application/javascript>
Webapp connected eth
        serving: /user.js <application/javascript>
Webapp connected eth
        serving: /customstepsjs.min-1.0.0.js <application/javascript>
Webapp connected eth
        serving: /layout1.jpg <image/jpeg>
Webapp connected eth
        serving: /short.gif <image/gif>
Webapp connected eth
        serving: /layout2.jpg <image/jpeg>
Webapp connected eth
        serving: /hold.gif <image/gif>
Webapp connected eth
        serving: /medium.gif <image/gif>
Webapp connected eth
        serving: /layout0.jpg <image/jpeg>
Webapp connected eth
        serving: /double.gif <image/gif>
Webapp connected eth
        serving: /eeprom.png <image/png>
Webapp connected eth
        serving: /favicon.ico <text/html>


Now if I use my real fileServer which also stream file for all requested file as it does for index, I get the following on ESP serial:

Webapp connected eth
        serving: /indexnozip.html <text/html>
Webapp connected eth
        serving: /style.css <text/css>
Webapp connected eth
        serving: /gettext.iife.min.js <application/javascript>
Webapp connected eth
        serving: /interval.js <application/javascript>
Webapp connected eth
        serving: /user.js <application/javascript>
Webapp connected eth
        serving: /customstepsjs.min-1.0.0.js <application/javascript>
Webapp connected eth
        serving: /layout1.jpg <image/jpeg>
Webapp connected eth
        serving: /layout2.jpg <image/jpeg>
Webapp connected eth
        serving: /vumeter.gif <image/gif>
Webapp connected eth
        serving: /short.gif <image/gif>
Webapp connected eth
        serving: /hold.gif <image/gif>
Webapp connected eth
        serving: /double.gif <image/gif>
Webapp connected eth
        serving: /eeprom.png <image/png>
**Webapp connected eth
Webapp connected eth**
        serving: /favicon.ico <text/html>
**Webapp connected eth
Webapp connected eth**
        serving: /connectivity.html <text/html>
Webapp connected eth
        serving: /layout1.jpg <image/jpeg>
Webapp connected eth
        serving: /user.html <text/html>
Webapp connected eth
        serving: /layout2.jpg <image/jpeg>
Webapp connected eth
        serving: /francais.json <application/json>
Webapp connected eth
        serving: /interval.ttf <font/ttf>
Webapp connected eth
        serving: /francais-user.json <application/json>
Webapp connected eth
        serving: /layout0.jpg <image/jpeg>Scan complete

in both case the "Webapp connected eth" comes from the main loop:
            EthernetClient newEthClient = ((EthernetServer*)hwm->configMedia->server)->available();
            if (newEthClient.connected()) {
              if (debug) Serial.println("\nWebapp connected eth");
              webServer->process(&newEthClient);
              newEthClient.stop();
            }            

On the browser console, I get:

GET http://192.168.0.135/layout0.jpg net::ERR_CONNECTION_REFUSED
GET http://192.168.0.135/medium.gif net::ERR_CONNECTION_REFUSED

which means 2 files where refused


My observation:
1) the issue always comes on image file (jpg or gif)
2) as highlightged in bold above, we exactly have 2 occurence of "Webapp connected eth" without having related "Serve...", which may lead to the conclusion that the webServer->process(&newEthClient); is not working correctly? 

I will continue investigation but if these test already ring you a bell, any input appreciated to orient them :-)

**Comment by infrafast** [comment]
Hello; I found the solution to that problem by buffering the output instead of sending char by char

for example instead of:

while (file.available()) res.write(file.read());

use:
      while ((bytesRead = file->read(buffer, BUFFER_SIZE)) > 0) {
        res->write(buffer, bytesRead);  // Écrire le tampon complet dans le client
      }
