### ISSUE TITLE
Can't read Content-Length header value

### ISSUE THREAD

**Issue by AleksaKolarski** [lasselukkari/aWOT#154]
Calling get("Content-Length") on request always returns NULL. I've managed to fix this by commenting out the Request::m_processHeaders first _if_ ( _if (m_expectP(ContentLength)) {_) and its block, along with else statement itself, keeping the content of the else block. Not sure if I broke something else by doing this, but so far it resolves the mystery for me :)
Ive just realized that by commenting that out Ive broke reading the body...
Never mind, I can just use left() :)

**Comment by lasselukkari** [comment]
The library needs to read that header internally to know when to stop reading. It's documented here: https://awot.net/en/3x/api.html#req-left
