### ISSUE TITLE
aWOT does not compile with Arduino on Ubuntu

### ISSUE THREAD

**Issue by pgollor** [lasselukkari/aWOT#2]
Hi all,
the aWOT library does not compile correctly on Ubuntu, because of line 24 in ```aWOT.cpp```:
```
#include <arduino.h>
```

I think it has to be ```<Arduino.h>```. But this line is not necessary, because the Arduino header is also included by ```aWOT.h```.

Without line 24 in ```aWOT.cpp``` it works very well.

I use:
- Ubuntu 14.04
- The latest Arduino IDE from github (version 1.6.6).
- Latest aWOT library from here

Greets
Kalle

**Comment by lasselukkari** [comment]
Sorry I didn't notice this earlier.

**Comment by lasselukkari** [comment]
Sorry I didn't notice this earlier.
