### ISSUE TITLE
error: 'class Response' has no member named 'success'

### ISSUE THREAD

**Issue by alessio-zamparelli** [lasselukkari/aWOT#29]
Hi, when I try to add the success response, it keep saying that class response has no member named succes.... This piece of code:
void statusCmd(Request &req, Response &res) {
  res.success("application/json");
  String currentStatus;
..........

Any idea?
Arduino ide for esp8266

**Comment by lasselukkari** [comment]
Hello!

The router examples in the readme are outdated. Thanks for letting me know. The success function was part of the pre 1.0 version API.

The default response code is 200 (success) so you don't need to set it if you don't want to use something else. To set the content type to json call 
```cpp
res.set("Content-Type", "application/json")
```

I will update the examples in the readme. The main documentations is available at [awot.com](https://awot.net/)

**Comment by alessio-zamparelli** [comment]
Thanks 🙏
