### ISSUE TITLE
SyntaxError: missing } after function body2.e33b5351.chunk.js:1:5878

### ISSUE THREAD

**Issue by thalesfsp** [lasselukkari/aWOT#31]
Followed the tutorial on how to serve static file. `npm start` (dev mode) runs OK, but after run
`build` and `dist`, I get this error: `SyntaxError: missing } after function body2.e33b5351.chunk.js:1:5878 ........`

**Comment by lasselukkari** [comment]
Hello! Where exactly you see this error? What OS do you have? Can you zip the whole project directory and attach it here.

I will be hiking for the next few days in the middle of nowhere. I'll get back  to you by the end of the week.

**Comment by thalesfsp** [comment]
I discovered that the problem was with my code :) Thank you!
