### ISSUE TITLE
Cant get request body because Request.body() is missing.

### ISSUE THREAD

**Issue by jvoj** [lasselukkari/aWOT#65]
Hi, in api 1.x there is a function of Request.body() which is used [in example here](https://awot.net/en/1x/api.html#req.body). But .body() function was removed by [this commit ](https://github.com/lasselukkari/aWOT/commit/d105d52e603649067d02ea3bcd0edbb13f7affb5#diff-3eea31c74b279e52e339ce9582a593b0) "in favor of functions inherited from Stream". 

Can you please create example or update docs to reflect stream api? I am struggling to find solution without the docs. 

Thanks for your great work! :)

**Comment by lasselukkari** [comment]
Thanks for reminding. I have not published the a new version for a while and the docs reflect the last published version. These api changes are breaking and will require a major version to be bumped. All help with updating the docs is greatly appreciated. The docs are located in the gh-pages branch.

The replacement for body is readBytes: https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadbytes/

You can also use all the other stream functions
- [find()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamfind)  
- [findUntil()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamfinduntil)  
- [peek()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streampeek/)  
- [readBytes()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadbytes)  
- [readBytesUntil()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadbytesuntil)  
- [readString()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadstring)  
- [readStringUntil()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamreadstringuntil)  
- [parseInt()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamparseint)  
- [parseFloat()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamparsefloat)  
- [setTimeout()](https://www.arduino.cc/reference/en/language/functions/communication/stream/streamsettimeout)

Also check the tests: https://github.com/lasselukkari/aWOT/blob/master/test/stream.cpp
