### ISSUE TITLE
Breaking changes 2.x -> 3.x

### ISSUE THREAD

**Issue by inetBrad** [lasselukkari/aWOT#83]
First - I really love the aWOT framework. It's been incredibly useful for creating an API-driven service on my ESP8266.

I recently updated from 2.x to 3.x and was surprised with some of the major changes that were not documented in any sort of release notes. The [online documentation](https://awot.net/en/3x/api.html) is accurate for 3.x, but makes no reference on changes required to upgrade from an older 2.x installation. 

In the future it would be helpful if there was a migration guide for breaking changes.

**Comment by lasselukkari** [comment]
Hi! Thanks for the feedback. It's really nice to hear you have found it useful.

Unfortunately I just did not have time to write a detailed changelog or upgrade guide. I barely had the time to update the API docs.

Would you like to participate writing such documents in the future if there is a new major version release with breaking changes? All help maintaining this project is really welcome. At the moment I'm taking care of this repository and the [awot-scripts](https://github.com/lasselukkari/awot-scripts) completely alone.

**Comment by lasselukkari** [comment]
I have now documented the breaking changes to the [v3.0.0 release notes](https://github.com/lasselukkari/aWOT/releases/tag/v3.0.0).
