### ISSUE TITLE
Curl hangs up when retrieving JSON on version 3

### ISSUE THREAD

**Issue by Jauwaad** [lasselukkari/aWOT#90]
Not sure this is because of HTTP 1.1. But the data is retrieved after the curl call times out.

**Comment by lasselukkari** [comment]
Please post an example sketch that that can be used to reproduce the problem.

**Comment by lasselukkari** [comment]
As expected the library does not close the socket automatically. It does not have destructor specified at all. https://github.com/arduino-libraries/WiFiNINA/blob/master/src/WiFiClient.h. Manually closing the client after processing should do the trick. This is the fist wifi library that I see working this way around. I will update the readme to contain a `compatibility` section.

**Comment by Jauwaad** [comment]
Calling client.stop() resolved this issue. Thanks for the help. Great library.
